### PR TITLE
Fixes for examples; Left/Right and Planck 

### PR DESCRIPTION
**Pull request by jurgen-kluft**
Left and Right split; both to include BFO9000.h and not define pinRow/pinCols and DATA/CLK again
Planck; ROWS/COLS did not match pinRow/pinCols array lengths

### CODE REVIEW

**Comment by colinta** [comment]
These look great, thanks for fixing them. I see a lot of whitespace changes - tabs vs spaces maybe? I can fix them on my end later - or would you mind checking your editor? I believe I was using 2-spaces as my “tab” setting

**Comment by jurgen-kluft** [comment]
Adjusted to spaces=2.

Would you like me to add a .clang-format file to the root, will help a lot in the future, kind of also documents your coding style. I use Visual Studio Code and the formatter used clang-format.

**Comment by colinta** [comment]
> Would you like me to add a .clang-format file to the root, will help a lot in the future, kind of also documents your coding style. I use Visual Studio Code and the formatter used clang-format.

Please!

**Comment by colinta** [comment]
Actually @jurgen-kluft I'm looking at the diff now... and I got the number of spaces wrong, it's 4 not 2, so sorry!

**Comment by colinta** [comment]
Thanks! LGTM

**Comment by jurgen-kluft** [comment]
That's ok, I will make it 4 spaces.

Are you Ok with adding the .clang-format file into the root of the repo?

**Comment by colinta** [comment]
That’s a great idea!

**Pull request merged**
